### ISSUE TITLE
NKN browser distribution is too big!

### ISSUE THREAD

**Issue by markg85** [nknorg/nkn-client-js#70]
Hi,

The minified browser package for NKN is about 700KB. That's really hefty!
Could something be done to make it, like, 10 times smaller (70KB is still big for a minified js library).

Cheers,
Mark

**Comment by yilunzhang** [comment]
We wanted to! But some of the dependencies we are using are quite heavy. We haven't identified which one specifically, but I guess it's crypto related or protobuf. I doubt whether if we can reduce the size significantly because it seems that all dependencies are necessary. But if I'm wrong that would be a good news!

Also you can turn on compression before serving the min.js file, which can reduce the file to around 200KB.

**Comment by markg85** [comment]
Could you give me the commands to generate those dist files? Then i'll have a look at it and see if there is something to be done here. Moment.js is also sucking up bytes like crazy.

No promises though :)

**Comment by yilunzhang** [comment]
Oh sure, simply `grunt dist` should be enough as long as you have grunt installed

**Comment by markg85** [comment]
> Oh sure, simply `grunt dist` should be enough as long as you have grunt installed

Awesome :) (never used grunt before).
I'll report back soon. (aka, within days)

**Comment by losnappas** [comment]
> Moment.js is also sucking up bytes like crazy.

Looking at its usage, is it really needed?

I only see https://github.com/nknorg/nkn-client-js/blob/f6756f9caae347be8793ac56e31dafdf06a86cb2/lib/client.js#L24-L29
and https://github.com/nknorg/nkn-client-js/blob/f6756f9caae347be8793ac56e31dafdf06a86cb2/lib/client.js#L89 using it. These could just as well be done with `new Moment()` -> `Date.now()`,  `now.add(...)` -> `now + timeout * 1000`, and `now.isAfter(..)` -> `now < deadline`

Am I missing something?

**Comment by yilunzhang** [comment]
> Looking at its usage, is it really needed?

You are right, I don't think we pay attention to how large Moment.js when using it 😂 

In version 0.7.1 (which enables native multicast + compression) and multiclient v0.1.0, we removed momentjs as you suggest, although the dist file is still around 700KB 😂

**Comment by markg85** [comment]
So, i hanen't been able to actually shrink this to normal proportions. As it requires touching large parts of the code. But i do have some findings..
1. Moment.js, the very first thing i noticed, seems useless in it's current use. But you already cought that :)
2. CryptoJS.. This will be more tricky to get out, but uses the vast amount of space. You could opt to use an abstraction that uses the crypto library on node.js and the SubtleCrypto [1] browser native support. It seems very fine to use it. As for a crypto wrapper, you'd need something to make either the node API usable in web or vice-versa. This [2] is a wrapper for SubtleCrypto in nodejs though i'm not sure how usable it is. Note that is is quite likely worth a good amount of time as you gain massive speed improvements with it too [3] (that's for webkit, but i suppose the same is true for chrome even though they are not the same engine anymore). On the other hand, i expect performance to only play a role if you make a file sharing service via NKN.

[1] https://caniuse.com/#feat=cryptography
[2] https://www.npmjs.com/package/subtle-crypto
[3] https://webkit.org/blog/7790/update-on-web-cryptography/

**Comment by yilunzhang** [comment]
We can forget about moment.js now since it's already gone :)

About CryptoJS, it's a bit tricky. If we switch to subtle crypto, then we have to break all our API in a backward-incompatible way from synchronized function to async function because all subtle crypto API, including hash and aes which we used, are async. And then we might be able to save around 50KB space, which is just ~7% of the total size...

**Comment by losnappas** [comment]
Might be worth it for the performance? Sending messages to a channel with many participants (#d-chat) is quite slow right now, although that might be because of bandwidth? Dunno.

50kb isn't a lot, so what's taking all the space?

**Comment by yilunzhang** [comment]
> Might be worth it for the performance? Sending messages to a channel with many participants (#d-chat) is quite slow right now, although that might be because of bandwidth? Dunno.

The performance has nothing to do with CryptoJS. Currently almost all of the time are spent on signature by TweetNacl library. The js version in browser is 100x or more slower than native version 😂 And I don't know any way to make it faster yet...

> 50kb isn't a lot, so what's taking all the space?

I think I know what's happening. 200KB+ space are used by protobuf, which we don't have much to do.

400KB+ are used by `lib/crypto/tools.js`, where 300KB+ are caused by this part:
```
var randomBytes;
if (typeof navigator != 'undefined' && navigator.product === "ReactNative") {
  randomBytes = require('crypto').randomBytes;
} else {
  randomBytes = nacl.randomBytes;
}
```
It's a polyfill for React Native to make the SDK usable on RN. We just need to get rid of this part in browserify by adding one exclude line in `Gruntfile.js` so the options looks line:
```
options: {
  exclude: ['crypto'],
  browserifyOptions: {
    standalone: 'nkn'
  }
}
```
Then the minified js become ~400KB, a lot smaller than before.

What I'm not sure is that whether it affects web-worker or not. @losnappas I remember that d-chat is using web-worker right? Could you please check whether adding this line will causing any trouble? Thanks!

**Comment by losnappas** [comment]
> The js version in browser is 100x or more slower than native version :joy:

Figures.

> @losnappas I remember that d-chat is using web-worker right? Could you please check whether adding this line will causing any trouble? Thanks!

Using web workers, yes, but also importing nkn-client (via nkn-multiclient) with an es6 import which is handled by webpack, so I'm not actually using the minified files and thus there should be no trouble for d-chat.

However, because webpack doesn't use the dist files, I'm not sure if this will help those of us who import it like that. Maybe there's an even better way..? I don't know it, though.

**Comment by yilunzhang** [comment]
> Figures.

The js version has benchmark result in github and also a one you can try yourself in browser: https://github.com/dchest/tweetnacl-js#benchmarks My laptop can sign 220+ msg/s in browser. For mobile it's around 60 (I haven't tested this one myself though)

The Go version can be tested using `go test -bench=. golang.org/x/crypto/ed25519` if you have Go installed. My laptop can sign 22k+ msg/s per core, 100x faster than js version on amd64.

The Java version can sign 10k+ msg/s based on our tests, almost 200x faster than js version on arm64.

The Go version can be cross compiled to Objective-C and Java library and achieve native performance.

> Using web workers, yes, but also importing nkn-client (via nkn-multiclient) with an es6 import which is handled by webpack, so I'm not actually using the minified files and thus there should be no trouble for d-chat.
> 
> However, because webpack doesn't use the dist files, I'm not sure if this will help those of us who import it like that. Maybe there's an even better way..? I don't know it, though.

For people who import using npm and pack himself, he can probably exclude `crypto` library when doing browserify or similar stuff to reduce those 300KB space.

**Comment by losnappas** [comment]
I have been paying some attention, and noticed that some libraries add
```json
"browser": {
  "crypto": false
}
```
into `package.json`, and I'm thinking webpack/browserify are smart enough to pick it up from there. That's probably what we should do as well.

**Comment by yilunzhang** [comment]
> I have been paying some attention, and noticed that some libraries add
> 
> ```json
> "browser": {
>   "crypto": false
> }
> ```
> 
> into `package.json`, and I'm thinking webpack/browserify are smart enough to pick it up from there. That's probably what we should do as well.

I just tested and you are right, this part has the same effect as excluding crypto in browserify config.

**Comment by yilunzhang** [comment]
Closed because nkn-client-js is deprecated in favor of [nkn-sdk-js](https://github.com/nknorg/nkn-sdk-js). We can continue our discussion there if needed.

**Comment by yilunzhang** [comment]
Good news: switching to libsodium (using wasm) can speed up signing by 50x+ :)
Bad news: it's adding ~288KB to the gzipped minified js :(

**Comment by sweco-nlmrag** [comment]
That's heavy...
But the performance win is heavy too :P

**Comment by markg85** [comment]
That's heavy...
But the performance win is heavy too :P
